# NUMPY
## Introduction Numpy
pustaka numpy berisi larik multidimensi dan struktur data matriks. Dapat digunakan untuk melakukan berbagai operasi matematika pada array. 

<b>installing Numpy</b>
dapat dengan <b>conda install numpy</b> atau <b>pip install numpy</b>

<b>How to import numpy</b>
import numpy as np #numpy dapat disingkat dengan np

<b>Why use numpy</b>
array numpy lebih cepat dan compact daripada list python. selain itu, lebih sedikit mengkonsumsi memory dan menyediakan mekanisme untuk menentukan tipe data

## Terminologi
<b>what is an array?</b>
yaitu grid of values dan berisi informasi tentang data mentah, cara menentukan elemen, dan cara mengintrepretasikan elemen. pengindeksan array dimulai dari 0. kelas ndarray numpy digunakan untuk mempresentasikan matriks & vektor.

<b>what are the atributes of an array?</b>
array atributes mencerminkan informasi intrinsik ke array itu sendiri

<b>what's the difference between a python list and a numpy array</b>
untuk membuat array numpy dapat menggunakan fungsi <b>np.array()</b>.

## Array
<b>Creating array</b>

In [2]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

ada metode seperti ones(), zeros() dll yang mana kita beri sejumlah elemen untuk di generate

In [3]:
#create ana rray filled with 0
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
#filled with 1
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
#or even an empty array
#the funct empty creates an array whose initial content is random & depends on the state of the memory
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
# create an array with a range of elemen
print(np.arange(4))
print(np.arange(0,10,2)) #(start,stop,step)

[0 1 2 3]
[0 2 4 6 8]


In [12]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

## Add,  Remove, and Sort

In [14]:
#menambahkan elemen ke array dgn np.append()
arr = np.array([1,2,3,4,5,6,7,8])
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [15]:
#menghapus elemen dngan np.delete()
np.delete(arr, 1) #menghapaus array index 1

array([1, 3, 4, 5, 6, 7, 8])

In [17]:
#mengurutkan elemen dengan np.sort
arr = np.array([2,5,1,3,7,4,8])
np.sort(arr)

array([1, 2, 3, 4, 5, 7, 8])

## Shape and Size
- <b>ndarray.ndim</b> : jumlah axes / dimensi array
- <b>ndarray.size</b> : jumlah total elemen array
- <b>ndarray.shape</b> : menampilkan tuple int yg menunjukkan jumlah elemen yg disimpan di seanjang dimensi array

In [18]:
arr_ex = np.array([[[0,1,2,3],
                    [4,5,6,7]],
                   
                   [[0,1,3,4],
                    [4,5,6,7]],
                  
                   [[0,1,3,4],
                    [4,5,6,7]]])

print(arr_ex)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 3 4]
  [4 5 6 7]]

 [[0 1 3 4]
  [4 5 6 7]]]


In [19]:
arr_ex.ndim

3

In [20]:
arr_ex.size

24

In [21]:
arr_ex.shape

(3, 2, 4)

In [22]:
arr_one = np.array([[1,2,3,4,5]])

In [23]:
arr_one.ndim

2

In [24]:
arr_one.size

5

In [25]:
arr_one.shape

(1, 5)

## Reshape
dapat menggunakan <b>np.reshape()</b>. apabila memakai itu array yg dihasilkan harus memiliki jummlah yg sama dgn array asli.

In [26]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [27]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [28]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [33]:
#numpy.reshape(vararray, newshape, order)
np.reshape(a, (6,1), 'F')

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Covert 1D to 2D
- np.newaxis = meningkatkan dimensi array sebesar i dimensi (1d -> 2d, 2d -> 3d dst)
- np.expand_dims = memperluas array dgn memasukkan axis baru pd posisi yg ditentukan

In [34]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [35]:
#you can use np.newaxis to add a new axis
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [36]:
#u can convert a 1d array to a row vector by inserting an axis along the first dimension
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [37]:
#for a column vector, u can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [38]:
#u can use np.epand_dims to add an axis at index position 1 with
b = np.expand_dims(a,axis=1)
b.shape

(6, 1)

In [39]:
#u can add an axis at index position 0 with:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## Indexing and Slicing

In [40]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [41]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
#u can easily print all of the values in the array that are less than 5
print(x[x>=5])

[ 5  6  7  8  9 10 11 12]


In [45]:
#cara lain
five_up = (x>=5)
print(x[five_up])
print(x[x>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [47]:
#u can select elements that are divisible by 2
divisible_by_2 = x[x%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [50]:
#u can select elements that satisfy 2 condition using the & and | operators
c = x[(x>2)&(x<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


## Creating array from existing data

In [51]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [52]:
#menumpuk dua array scr vertikaldengan vstack 
a_1 = np.array([[1,1],
                [2,2]])

a_2 = np.array([[3,3],
                [4,4]])

np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [53]:
#stack them horizontally with hstack
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [55]:
#membagi sebuah array menjadi beberapa array yg lebih keil dgn hsplit
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
                     [13,14,14,16,17,18,19,20,21,22,23,24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 14 16 17 18 19 20 21 22 23 24]]


In [59]:
#if u wanted to split this array into three equally shaped arrays
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 14, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [63]:
a = arrsplit
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [62]:
#metode view utk membuat objek array baru yang terlihat sama dengan array asli
b = arrsplit.view()
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [65]:
#using copy method will make a complete copy of the array and its data (a deep copy)
c = a.copy()
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

## Basic array operations

In [67]:
a = np.array([1,2,3,4])

# add all of elements on the array
a.sum()

10

In [68]:
#utk menambahkan baris / kolom dalam array 2d, harus menentukan axis
b = np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [69]:
#u can sum the rows
b.sum(axis=0)

array([3, 3])

In [70]:
#u can sum the colums
b.sum(axis=1)

array([2, 4])

In [71]:
data = np.array([1,2])
data

array([1, 2])

In [72]:
ones = np.ones(2)
ones

array([1., 1.])

In [73]:
data + ones

array([2., 3.])

In [74]:
data*ones

array([1., 2.])

In [75]:
data*data

array([1, 4])

In [76]:
data/data

array([1., 1.])

## Broadcasting
yaitu mekanisme yg memungkinkan numpy melakukan operasi pada array dengan bentuk berbeda. dimensi array harus kompatibel

In [77]:
data*2

array([2, 4])

### Function
Beberapa fungsi utilitas dasar dari modul np.random adalah np.random.seed dan np.random.shuffle. Kami menggunakan fungsi np.random.seed untuk mengatur random seed, yang memungkinkan kami untuk mengontrol output dari fungsi pseudo-random. Fungsi mengambil satu bilangan bulat sebagai argumen, yang mewakili random seed.

Kode di bawah ini menggunakan np.random.seed dengan seed random yang sama. Perhatikan bagaimana output dari 
fungsi random di setiap proses berikutnya adalah identik ketika ditetapkan random seed yang sama.
Beberapa fungsi utilitas dasar dari modul np.random adalah np.random.seed dan np.random.shuffle. 

Dalam menggunakan fungsi np.random.seed untuk mengatur random seed, yang memungkinkan dilakukan 
untuk mengontrol output dari fungsi pseudo-acak. Fungsi mengambil satu bilangan bulat sebagai argumen, 
yang mewakili random seed.

Kode di bawah ini menggunakan np.random.seed dengan seed acak yang sama. 
Perhatikan bagaimana output dari fungsi random di setiap proses berikutnya adalah identik ketika 
kita menetapkan random seed yang sama.

In [15]:
np.random.seed(0)
print(np.random.randint(10))

5


In [16]:
random_arr = np.random.randint(10,100,6) # dari 10 ke 100 sebanyak 6 
print(random_arr)

[74 77 77 19 93 31]


In [17]:
np.random.seed(0)
random_arr = np.random.randint(3, high=100,
                               size=(2, 2)) ## randint(low, high=None, size=None, dtype=int)

print(repr(random_arr))

array([[47, 50],
       [67, 70]])


In [18]:

# New seed
np.random.seed(2)

random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

array([[43, 18],
       [75, 25]])


In [19]:

# Original seed
np.random.seed(0)
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

array([[47, 50],
       [67, 70]])


## More array operation

In [79]:
A = np.array([[0.45, 0.17, 0.34, 0.55],
              [0.54, 0.05, 0.40, 0.55],
              [0.12, 0.82, 0.26, 0.56]])
print(A)

[[0.45 0.17 0.34 0.55]
 [0.54 0.05 0.4  0.55]
 [0.12 0.82 0.26 0.56]]


In [80]:
A.sum()

4.8100000000000005

In [81]:
A.min()

0.05

In [82]:
A.min(axis=0)

array([0.12, 0.05, 0.26, 0.55])

In [83]:
A.max()

0.82

In [84]:
A.max(axis=1)

array([0.55, 0.55, 0.82])

In [85]:
A.std()

0.21332519515727366

## Save array into file

In [20]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)


[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [21]:
np.save("myarray2.npy",A)

In [22]:
responseFile = np.load('myarray2.npy')
print(responseFile)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


## Latihan 

* Buat lah Array 
```
[[  0  72   3]
 [  1   3 -60]
 [ -3  -2   4]]
``` 

Simpan file Array tersebut 
Kemudian lakukan load file Array 

lakukan pencarian data dibawah ini 

Temukan Nilai minum dan maksimum pada file tersebut 

Temukan Nilai minum di setiap kolom 
Temukan Nilai Maksimum di setiap Kolom 
Menemukan Nilai Minimum di setiap baris 
Menemukan Nilai Maksimum di setiap baris 

In [24]:
h = np.array([[0,72,3],
              [1,3,-60],
              [-3,-2,4]])
print(h)

[[  0  72   3]
 [  1   3 -60]
 [ -3  -2   4]]


In [25]:
np.save("arrayLatihan.npy",h)

In [26]:
responseFile = np.load('arrayLatihan.npy')
print(responseFile)

[[  0  72   3]
 [  1   3 -60]
 [ -3  -2   4]]


In [28]:
# nilai minimum
responseFile.min()

-60

In [29]:
#nilai maximum
responseFile.max()

72

In [30]:
#nilai min axis 1
responseFile.min(axis=1)

array([  0, -60,  -3])

In [31]:
#niai max axis 1
responseFile.max(axis=1)

array([72,  3,  4])

In [32]:
#nilai min axis 0
responseFile.min(axis=0)

array([ -3,  -2, -60])

In [33]:
#nilai ma axis 0
responseFile.max(axis=0)

array([ 1, 72,  4])

# Latihan Studi Kasus 

10 buah botol minum akan dibuat untuk menyimpan air dengan jari2 dan tinggi yang berbeda - beda . 
Besaran jari2 dan tinggi botol adalah bilang bulat kisaran 7 sampai dengan 20 cm . 

Temukan : 

1. Volume air yang dapat disimpan di setiap botol 
2. Total volume air yang tersimpan dalam semua botol 
3. Botol mana yang volume air terkecil dan temukan volumenya 
4. Botol mana yang menampung volume air terbesar dan temukan volume airnya . 
5. Rata-rata volume yang dapat di tampung di tiap botol 

Solusi : 
1. Lakukan generate tinggi botol dan jari2 
2. Punya batasan 7 sampai 20 , kemudian sebanyak 10 
   Dengan kata lain harus mengenerate sebanyak 20 
3. Membentuk botol sebanyak 10 buah (tinggi dan jari2) 
4. Setelah terbentuk botol mencari volume air masing botol 
   Volume air = (Pi x r^2 x t ) untuk numpy pi = np.pi 
5. Mencari Total volume air dalam semua botol sum 
6. Mencari botol yang terkcil dan temukan volume nya 
7. Mencari botol yang terbesar dan temukan volume nya 
8. Mencari rata2 dengan mean 

## Matrices
## Creating Matrices


In [86]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.89773394 0.83426633]
 [0.87443992 0.56090435]
 [0.75788093 0.81549289]]


## Matrix Arithmetic

In [87]:
data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [88]:
ones =np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [89]:
print(data+ones)

[[2. 3.]
 [4. 5.]]


In [93]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [94]:
print(data+ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product
dot() dapst digunakan utk menjalankan operasi dot product dengan matriks lain

In [95]:
a_1 = np.array([[1,2,3],[4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8],[9,10],[11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [96]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])

## Matrix Indexing

In [97]:
data = np.array([[1,2],[3,4],[5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Agregation

In [98]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [99]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [101]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing and Reshaping

In [102]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [103]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [104]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [105]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [107]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensional Array

In [109]:
ndarr = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [110]:
#berurusan dgn dimensi baru, hanyalah dgn menambahkan koma ke parameter fungsi numpy
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [111]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [112]:
print(np.random.random((4,3,2)))

[[[0.50552943 0.53255083]
  [0.88662933 0.38533576]
  [0.92705995 0.22932001]]

 [[0.87633239 0.34739562]
  [0.73932311 0.68370065]
  [0.01776103 0.97266843]]

 [[0.63400516 0.40928904]
  [0.64119968 0.57564517]
  [0.93004309 0.1365263 ]]

 [[0.37831783 0.55661849]
  [0.77321676 0.36254476]
  [0.19089159 0.36700538]]]


## Flatten N-Dimensional Array
ravel tidal membuat salinan jadi menghemat memori

In [113]:
arrflat= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [114]:
#u can use flatten to flatten your array into a 1d array
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas


In [115]:
error = (1/n) * np.sum(np.square(observed - prediction))

NameError: name 'n' is not defined

## Tips Py
<b>Notes on Numpy Vector</b>

In [3]:
#ketika membuat numpy array dengan commmand seperti ini
a = np.random.rand(5)
print(a)

[0.93146989 0.32229054 0.67065743 0.74836028 0.33125619]


In [4]:
#kalian akan mendapatkan hasil output shape seprti dibawah
a.shape #rank 1 array

#kita akan mendapat output berupa shape hanya 1 angka dan sering disebut dengan Rank 1 array

(5,)

In [5]:
#apa yg terjadi ketika kita ingin melakukan operasi transpose terhadap rank 1 array?
print(a.T)

#Bentuknya tdk akan berubah, masih sama spt bentuk awalnya

[0.93146989 0.32229054 0.67065743 0.74836028 0.33125619]


In [6]:
#Apa yg terjadi ketika kita melakukan operasi dot produk pada rank 1 array tsb?
print(np.dot(a,a.T))

#Operasi yg dilakukan tdk menunjukkan hasil yg seharusnya.
#Karena rank 1 array hanya mempunyai baris atau kolom saja

2.0910625303580583


Tips membuat array adalah selalu memasukkan 2 argumen ketika akan membuat column ataupun row vevtor. seperti contoh dibawah memasukkan 5 dan 1 sebagai argumen

In [8]:
a = np.random.rand(5,1) #column vector
print(a)

[[0.56666934]
 [0.95724627]
 [0.57951103]
 [0.79215335]
 [0.27350647]]


In [9]:
#ketika kita transpose, bentuknya akan berubah
print(a.T)

[[0.56666934 0.95724627 0.57951103 0.79215335 0.27350647]]


In [10]:
#Dan ketika melakukan operasi dot product, hasilnya akan sesuai seperti yg diharapkan
print(np.dot(a, a.T))

[[0.32111414 0.54244211 0.32839113 0.44888902 0.15498773]
 [0.54244211 0.91632043 0.55473477 0.75828584 0.26181305]
 [0.32839113 0.55473477 0.33583304 0.45906161 0.15850002]
 [0.44888902 0.75828584 0.45906161 0.62750693 0.21665907]
 [0.15498773 0.26181305 0.15850002 0.21665907 0.07480579]]


In [13]:
#begitu pula dengan row vector
a = np.random.rand(1,5)
print(a)

[[0.17395267 0.0802409  0.9377599  0.52851074 0.90090611]]


Don' use rank 1 Array: Always use 1 by n matrices or n by 1 matrices instead. (column or row vectors)